import { defineConfig } from 'vite';
import { resolve } from 'path';
import react from '@vitejs/plugin-react';
import { vitePrerenderPlugin } from 'vite-prerender-plugin';

export default defineConfig({
  envPrefix: ['VITE_', 'NEXT_PUBLIC_'],
  plugins: [
    react(),
    vitePrerenderPlugin({
      renderTarget: '#root',
      prerenderScript: resolve(__dirname, 'src', 'prerender.jsx'),
      additionalPrerenderRoutes: [
        '/', '/hizmetler', '/psiko-beslenme', '/duygusal-yeme',
        '/online-terapi', '/uzmanlik-alanlari', '/hakkimizda',
        '/iletisim', '/blog', '/admin', '/site-haritasi',
        '/blog/psiko-beslenme-nedir',
        '/blog/duygusal-yeme-dongusu',
        '/blog/online-terapi-verimli-mi',
        '/blog/izmir-psikolog-rehberi',
        '/blog/stres-ve-beslenme',
        '/blog/izmir-diyetisyen-rehberi',
        '/blog/pcos-ve-beslenme',
        '/blog/bilincli-yeme-mindful-eating',
        '/blog/sosyal-kaygi-ve-terapi',
        '/blog/depresyon-ve-beslenme',
        '/blog/cocuklarda-saglikli-beslenme',
        // tag pages
        '/blog/etiket/psiko-beslenme',
        '/blog/etiket/butuncul-saglik',
        '/blog/etiket/psikolog',
        '/blog/etiket/diyetisyen',
        '/blog/etiket/duygusal-yeme',
        '/blog/etiket/stres-yonetimi',
        '/blog/etiket/yeme-bozuklugu',
        '/blog/etiket/terapi',
        '/blog/etiket/online-terapi',
        '/blog/etiket/uzaktan-terapi',
        '/blog/etiket/d-p',
        '/blog/etiket/izmir-psikolog',
        '/blog/etiket/terapi-rehberi',
        '/blog/etiket/alsancak',
        '/blog/etiket/uzman-secimi',
        '/blog/etiket/kortizol',
        '/blog/etiket/beslenme',
        '/blog/etiket/stres',
        '/blog/etiket/izmir-diyetisyen',
        '/blog/etiket/diyetisyen-rehberi',
        '/blog/etiket/kilo-yonetimi',
        '/blog/etiket/pcos',
        '/blog/etiket/polikistik-over',
        '/blog/etiket/hormon-beslenme',
        '/blog/etiket/insulin-direnci',
        '/blog/etiket/kadin-sagligi',
        '/blog/etiket/mindful-eating',
        '/blog/etiket/bilincli-yeme',
        '/blog/etiket/farkindalik',
        '/blog/etiket/saglikli-beslenme',
        '/blog/etiket/sosyal-kaygi',
        '/blog/etiket/kaygi-bozuklugu',
        '/blog/etiket/bdt',
        '/blog/etiket/depresyon',
        '/blog/etiket/omega-3',
        '/blog/etiket/bagirsak-beyin-ekseni',
        '/blog/etiket/ruh-sagligi',
        '/blog/etiket/cocuk-beslenmesi',
        '/blog/etiket/yemek-secme',
        '/blog/etiket/ebeveyn-rehberi',
        '/blog/etiket/aile',
        // category pages
        '/blog/kategori/psiko-beslenme',
        '/blog/kategori/duygusal-yeme',
        '/blog/kategori/online-terapi',
        '/blog/kategori/rehber',
        '/blog/kategori/beslenme',
        '/blog/kategori/psikoloji',
        // service detail pages
        '/hizmetler/bireysel-psikolojik-danismanlik',
        '/hizmetler/kisiye-ozel-beslenme',
        '/hizmetler/psiko-beslenme',
        '/hizmetler/online-seans',
        '/hizmetler/kadin-sagligi-beslenme',
        '/hizmetler/kurumsal-wellbeing',
        // location pages
        '/izmir/alsancak-psikolog',
        '/izmir/karsiyaka-diyetisyen',
        '/izmir/bornova-psikolog',
        '/izmir/karsiyaka-psikolog',
        '/izmir/alsancak-diyetisyen',
        '/izmir/bornova-diyetisyen'
      ],
      previewMiddlewareFallback: '/404'
    })
  ]
});
